# Priority labels
- name: "priority: critical"
  color: "d73a4a"
  description: "Critical priority issue"

- name: "priority: high"
  color: "f9c513"
  description: "High priority issue"

- name: "priority: medium"
  color: "7057ff"
  description: "Medium priority issue"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority issue"

# Type labels
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type: enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "type: documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "type: performance"
  color: "f9c513"
  description: "Performance improvements"

- name: "type: refactor"
  color: "0e8a16"
  description: "Code refactoring"

# Status labels
- name: "status: needs-review"
  color: "fbca04"
  description: "Waiting for review"

- name: "status: in-progress"
  color: "0052cc"
  description: "Currently being worked on"

- name: "status: blocked"
  color: "d73a4a"
  description: "Blocked by another issue or dependency"

- name: "status: help-wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "status: good-first-issue"
  color: "7057ff"
  description: "Good for newcomers"

# Component labels
- name: "component: parser"
  color: "c5def5"
  description: "Related to parser functionality"

- name: "component: types"
  color: "c5def5"
  description: "Related to TypeScript types"

- name: "component: tests"
  color: "c5def5"
  description: "Related to testing"

- name: "component: build"
  color: "c5def5"
  description: "Related to build system"

- name: "component: ci"
  color: "c5def5"
  description: "Related to CI/CD"

# Special labels
- name: "breaking-change"
  color: "d73a4a"
  description: "Breaking API change"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on" 